#!/bin/bash

WALLPAPER_DIR="$HOME/walls"


FILES=$(find "$WALLPAPER_DIR" -type f \( -iname '*.jpg' -o -iname '*.png' \) -printf '%f\n')


selected=$(echo "$FILES" | wofi --prompt="Select Wallpaper" --show=dmenu)


if [[ -n "$selected" ]]; then
    # Önce swaybg varsa kapat
    pkill swaybg

 
    swaybg -i "$WALLPAPER_DIR/$selected" -m fill &
fi
