#!/bin/bash

WALLPAPER_DIR="$HOME/Wallpapers"

FILES=$(find "$WALLPAPER_DIR" -type f \( -iname '*.jpg' -o -iname '*.png' -o -iname '*.jpeg' \))

selected=$(echo "$FILES" | xargs -n1 basename | wofi --prompt="Select Wallpaper" --show=dmenu)

if [[ -n "$selected" ]]; then
    pkill swaybg
    swaybg -i "$WALLPAPER_DIR/$selected" -m fill &
fi