#!/bin/bash
if [ -f /etc/os-release ]; then
    . /etc/os-release
    DISTRO=$ID
    VARIANT=$VARIANT_ID
else
    DISTRO=$(uname -s)
fi

case "$DISTRO" in
    fedora)
        if [[ "$VARIANT" == *"silverblue"* || "$VARIANT" == *"kinoite"* || "$VARIANT" == *"atomic"* ]]; then
            sudo rpm-ostree install git nano sway waybar wofi nwg-drawer nwg-look fastfetch curl meson ninja-build gcc make pkg-config swaybg
        else
            sudo dnf install -y git nano sudo sway waybar wofi nwg-drawer nwg-look fastfetch curl meson ninja-build gcc make pkg-config swaybg
        fi
        ;;
    ubuntu|debian|kali)
        sudo apt update
        sudo apt install -y git nano sudo sway waybar wofi nwg-drawer nwg-look fastfetch curl build-essential meson ninja-build pkg-config swaybg
        ;;
    arch|manjaro)
        sudo pacman -Syu --noconfirm git nano sudo sway waybar wofi nwg-drawer nwg-look fastfetch curl base-devel meson ninja swaybg
        if [[ "$DISTRO" == "manjaro" ]]; then
            sudo pacman -S --noconfirm yay
        else
            if ! command -v yay &> /dev/null; then
                git clone https://aur.archlinux.org/yay.git ~/Downloads/yay
                cd ~/Downloads/yay
                makepkg -si --noconfirm
                cd ~
            fi
        fi
        ;;
    opensuse*)
        sudo zypper install -y git nano sudo sway waybar wofi nwg-drawer nwg-look fastfetch curl make gcc meson ninja-build pkg-config swaybg
        ;;
    gentoo)
        sudo emerge --ask app-editors/nano app-editors/git sudo x11-wm/sway x11-wm/waybar wofi nwg-drawer fastfetch curl dev-util/meson dev-util/ninja x11-misc/swaybg
        ;;
    *)
        echo "Unknown distribution, please install packages manually."
        ;;
esac

curl -sS https://starship.rs/install.sh | sh
git clone https://github.com/maxuwuu/walls.git ~/Downloads/walls
git clone https://github.com/maxuwuu/swayconf.git ~/Downloads/swayconf

if ! command -v rofi &> /dev/null; then
    git clone --recursive https://github.com/in0ni/rofi-wayland.git ~/Downloads/rofi-wayland
    cd ~/Downloads/rofi-wayland
    mkdir -p build && cd build
    meson ..
    ninja
    sudo ninja install
    cd ~
fi

cp -r ~/Downloads/swayconf/waybar/* ~/.config/waybar/
cp -r ~/Downloads/swayconf/wofi/* ~/.config/wofi/
cp -r ~/Downloads/swayconf/rofi/* ~/.config/rofi/
cp -r ~/Downloads/swayconf/nwg-drawer/* ~/.config/nwg-drawer/
cp -r ~/Downloads/swayconf/sway/* ~/.config/sway/
cp -r ~/Downloads/swayconf/Terminal/fastfetch ~/.config/
cp ~/Downloads/swayconf/Terminal/starship.toml ~/.config/starship.toml
cat ~/Downloads/swayconf/Terminal/.bashrc >> ~/.bashrc
