#!/bin/bash

WALLPAPER_DIR="$HOME/walls"

FILES=$(find "$WALLPAPER_DIR" -type f \( -iname '*.jpg' -o -iname '*.png' -o -iname '*.jpeg' \))

selected=$(echo "$FILES" | xargs -n1 basename | rofi -dmenu -p "Select Wallpaper")

if [[ -n "$selected" ]]; then
    pkill swaybg
    swaybg -i "$WALLPAPER_DIR/$selected" -m fill &
fi