#!/bin/bash

WALLPAPER_DIR="$HOME/walls"

# Klasördeki .jpg ve .png dosyalarını bul ve isimlerini listele
FILES=$(find "$WALLPAPER_DIR" -type f \( -iname '*.jpg' -o -iname '*.png' \) -printf '%f\n')

# Wofi ile seçim yap
selected=$(echo "$FILES" | wofi --prompt="Select Wallpaper" --show=dmenu)

# Seçim yapıldıysa
if [[ -n "$selected" ]]; then
    # Önce swaybg varsa kapat
    pkill swaybg

    # Yeni wallpaper uygula
    swaybg -i "$WALLPAPER_DIR/$selected" -m fill &
fi